import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

import newPostPackage.newPost;

/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    public Editor() {}

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"
        System.out.println(request.getMethod());
        String username = request.getParameter("username");
        if (username == null || username == ""){
            username = "Hoang";
        }
        System.out.println("Username: ");
        System.out.println(username);
        request.setAttribute("username", username);

        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        int counter = -1;
        try{
            con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/CS144", "cs144", ""
            );
            ps = con.prepareStatement("SELECT MAX(postid) FROM Posts WHERE username=?");
            ps.setString(1, username);
            rs = ps.executeQuery();
            while(rs.next()){
                int temp = (int) rs.getObject(1);
                System.out.println(temp);
                counter = temp;
            }
        } catch (SQLException ex){
            System.out.println(ex);
        } finally{
            if (rs != null){
                try{
                    rs.close();
                } catch(SQLException e){}
            }
            if (ps != null){
                try{
                    ps.close();
                } catch(SQLException e){}
            }
            if (con != null){
                try{
                    con.close();
                } catch(SQLException e){}
            }
        }
        request.setAttribute("postid", counter + 1);
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"
        System.out.println("POST");
        String action = request.getParameter("action");
        //String body = request.getParameter("body");

        //System.out.println(body + " " + request.getParameter("title"));
        if(action.equals("save") ){
            handleSave(request, response);
        } else if(action.equals("delete")){
            handleDelete(request, response);
        } else if(action.equals("close")){
            fetchList(request, response);
        } else if(action.equals("preview")){
            handlePreview(request, response);
        } else if(action.equals("open")){
            System.out.println("This is the handler values");
            System.out.println(request.getParameter("body"));
            handleOpen(request, response);
        }
        else{
            request.getRequestDispatcher("/invalid.jsp").forward(request, response);
        }

        
    }
    
    /** handleSave handles the Save functionality on the edit page
    */
    public void handleSave(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        String title = request.getParameter("title");
        String body = request.getParameter("body");
        String username = request.getParameter("username");
        String pid = request.getParameter("postid");
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/CS144", "cs144", ""
            );
            int pid_counter = 0;
            if(pid == "" || pid == null){
                ps = con.prepareStatement("SELECT postid FROM Posts WHERE username = ? ORDER BY created DESC LIMIT 1");
                ps.setString(1, username);
                rs = ps.executeQuery();
                if (rs.next()){
                    pid_counter = rs.getInt("postid") + 1;
                }
                System.out.println("NewPost");
            }
            else{
                System.out.println("EditedPost");
                System.out.println(pid);
                pid_counter = Integer.parseInt(pid);
            }

            ps = con.prepareStatement("IF EXISTS(SELECT * FROM Posts WHERE username=? AND postid=?) THEN UPDATE Posts SET title = ?, body = ?, modified = ? WHERE postid=? AND username=?; ELSE INSERT INTO Posts VALUES(?, ?, ?, ?, ?, ?); END IF");
            Timestamp ts = new Timestamp(System.currentTimeMillis());
            String modified = ts.toString();
            ps.setString(1, username);
            ps.setInt(2, pid_counter);
            ps.setString(3, title);
            ps.setString(4, body);
            ps.setString(5, modified);
            ps.setInt(6, pid_counter);
            ps.setString(7, username);
            ps.setString(8, username);
            ps.setInt(9, pid_counter);
            ps.setString(10, title);
            ps.setString(11, body);
            ps.setString(12, modified);
            ps.setString(13, modified);
            ps.executeUpdate();
        } catch (SQLException ex){
            System.out.println(ex);
        } finally{
            if (rs != null){
                try{
                    rs.close();
                } catch(SQLException e){}
            }
            if (ps != null){
                try{
                    ps.close();
                } catch(SQLException e){}
            }
            if (con != null){
                try{
                    con.close();
                } catch(SQLException e){}
            }
        }
        fetchList(request, response);
    }


    /*
        handleClose handles the close functionality of the close button on the edit page
    */
    public void fetchList(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        //String title = request.getParameter("title");
        //String body = request.getParameter("body");
        String username = request.getParameter("username");
        request.setAttribute("username", username);
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/CS144", "cs144", ""
            );
            ps = con.prepareStatement("SELECT title, created, modified, postid, username FROM Posts WHERE username = ? ORDER BY postid");
            ps.setString(1, username);
            rs = ps.executeQuery();
            ArrayList<newPost> newPostList = new ArrayList();
            while(rs.next()){
                newPost p = new newPost();
                p.setTitle((String) rs.getObject(1));
                p.setModified((Timestamp) rs.getObject(3));
                p.setCreated((Timestamp) rs.getObject(2));
                p.setPostid((int) rs.getObject(4));
                p.setUsername((String) rs.getObject(5));
                newPostList.add(p);
            }
            request.setAttribute("resultList", newPostList);
        } catch (SQLException ex){
            System.out.println(ex);
        } finally{
            if (rs != null){
                try{
                    rs.close();
                } catch(SQLException e){}
            }
            if (ps != null){
                try{
                    ps.close();
                } catch(SQLException e){}
            }
            if (con != null){
                try{
                    con.close();
                } catch(SQLException e){}
            }
        }
        request.getRequestDispatcher("/list.jsp").forward(request, response);
    }

    public void handleDelete(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        String tempid = request.getParameter("postid");
        if(tempid == null){
            System.out.println("postid was null");
            fetchList(request, response);
            return;
        }
        System.out.println("postid was not null");
        System.out.println(tempid);
        int postid = Integer.parseInt(request.getParameter("postid"));
        String username = request.getParameter("username");
        System.out.println(username);
        Connection con = null;
        PreparedStatement ps = null;
        try{
            con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/CS144", "cs144", ""
            );
            ps = con.prepareStatement("DELETE FROM Posts WHERE username = ? AND postid = ?");
            ps.setString(1, username);
            ps.setInt(2, postid);
            ps.executeUpdate();
        } catch(SQLException ex){
            System.out.println(ex);
        } finally{
            if (ps != null){
                try {
                    ps.close();
                } catch (SQLException e){}
            }
            if (con != null){
                try{
                    con.close();
                } catch (SQLException e){}
            }
        }
        fetchList(request, response);


    }

    public void handleOpen(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        request.setAttribute("postid", request.getParameter("postid"));
        request.setAttribute("username", request.getParameter("username"));
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            if (request.getParameter("body") != null){
                request.setAttribute("title", request.getParameter("title"));
                request.setAttribute("body", request.getParameter("body"));
                System.out.println("found a body/title");
                System.out.println(request.getParameter("body"));
            }
            else{
                System.out.println("Did not find a body/title");
                con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/CS144", "cs144", ""
                );
                ps = con.prepareStatement("SELECT title, body FROM Posts WHERE username=? AND postid=?");
                ps.setString(1, request.getParameter("username"));
                ps.setInt(2, Integer.parseInt(request.getParameter("postid")));
                rs = ps.executeQuery();
                while (rs.next()){
                    request.setAttribute("title", rs.getObject(1));
                    request.setAttribute("body", rs.getObject(2));
                }
            }
        } catch(SQLException ex){
            System.out.println(ex);
        } finally{
            if (rs != null){
                try{
                    rs.close();
                } catch (SQLException e){}
            }
            if (ps != null){
                try{
                    ps.close();
                } catch (SQLException e){}
            }
            if (con != null){
                try{
                    con.close();
                } catch (SQLException e){}
            }
        }
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }

    public void handlePreview(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        String title, body;
        title = request.getParameter("title");
        body = request.getParameter("body");

        Parser parser = Parser.builder().build();
        Node document = parser.parse(title);
        HtmlRenderer renderer = HtmlRenderer.builder().build();
        String title_rendered = renderer.render(document);
        request.setAttribute("title_rendered", title_rendered);

        Node document2 = parser.parse(body);
        String body_rendered = renderer.render(document2);
        request.setAttribute("body_rendered", body_rendered);

        request.setAttribute("username", request.getParameter("username"));
        request.setAttribute("postid", request.getParameter("postid"));
        request.setAttribute("body", body);
        request.setAttribute("title", title);
        System.out.println(body);

        request.getRequestDispatcher("/preview.jsp").forward(request, response);
    }
}

